# Generated by Django 3.1 on 2020-08-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobModel', '0002_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='info',
            field=models.CharField(default='', max_length=500),
        ),
    ]
