# Generated by Django 3.1 on 2020-08-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobModel', '0003_recruiter_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('describe', models.CharField(default='', max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('requirement', models.CharField(max_length=500)),
                ('received_resume', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
