# Generated by Django 3.1 on 2020-08-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobModel', '0005_job_item_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_item',
            name='interview_resume',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
